---
abstract: 'Test Web applications using TAP'
author:
  - 'Joe McMahon <mcmahon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Simple
no_index:
  directory:
    - t
    - inc
requires:
  HTML::Tree: 0
  Mojolicious::Lite: 0
  Regexp::Common: 0
  Test::Builder: 0
  Test::LongString: 0
  Test::Tester: 0
  WWW::Mechanize: 0
  WWW::Mechanize::Pluggable: 1.07
version: 0.34
