--- #YAML:1.0
name:               Test-WWW-Simple
version:            0.33
abstract:           Test Web applications using TAP
author:
    - Joe McMahon <mcmahon@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::Parser:         0
    HTML::Tree:           0
    Mojolicious::Lite:    0
    Regexp::Common:       0
    Test::Builder:        0
    Test::LongString:     0
    Test::Tester:         0
    WWW::Mechanize:       0
    WWW::Mechanize::Pluggable:  1.07
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
